---
# Service: service-a-v1-0-0
apiVersion: v1
kind: Service
metadata:
  name: service-a-v1-0-0
  namespace: demo
spec:
  selector:
    app: service-a
    version: 1.0.0
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# Deployment: service-a-v1-0-1-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v1-0-1-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: 1.0.1
      host: acme-api
  template:
    metadata:
      labels:
        app: service-a
        version: 1.0.1
        host: acme-api
    spec:
      serviceAccountName: service-a
      containers:
      - name: service-a
        image: patrice1972/scenario-01-service-a:1.0.1
        ports:
        - name: service-a-port
          protocol: TCP
          containerPort: 3000
---
# Service: service-a-v1-0-1
apiVersion: v1
kind: Service
metadata:
  name: service-a-v1-0-1
  namespace: demo
spec:
  selector:
    app: service-a
    version: 1.0.1
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
