# uc-01-step-02.k8s-with-consul.yaml
---
# Deploy 'service-a-v1-1-0-deployment' Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v1-1-0-deployment
  namespace: consul-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: 1.1.0
  template:
    metadata:
      labels:
        app: service-a
        version: 1.1.0
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "service-a"
        "consul.hashicorp.com/connect-service-port": "service-a-port"
    spec:
      serviceAccountName: service-a
      containers:
      - name: service-a
        image: patrice1972/service-a:1.1.0
        ports:
        - name: service-a-port
          protocol: TCP
          containerPort: 3000
