# uc-01-step-02.2nd-k8s-for-smi.yaml
---
# Deploy 'service-a-v1-0-0' Service
apiVersion: v1
kind: Service
metadata:
  name: service-a-v1-0-0
  namespace: demo
spec:
  selector:
    app: service-a
    version: 1.0.0
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# Deploy 'service-a-v1-1-0' Service
apiVersion: v1
kind: Service
metadata:
  name: service-a-v1-1-0
  namespace: demo
spec:
  selector:
    app: service-a
    version: 1.1.0
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000