---
# Deploy 'service-a-v2-0-0-deployment' Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v2-0-0-deployment
  namespace: routing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: 2.0.0
  template:
    metadata:
      labels:
        app: service-a
        version: 2.0.0
        api: alpha-api
    spec:
      serviceAccountName: service-a
      containers:
      - name: service-a
        image: patrice1972/routing-demo-service-a:2.0.0
        ports:
        - protocol: TCP
          containerPort: 3000
