swagger: '2.0'
info:
  title: Alpha API
  version: 1.1.0
host: acme-api
basePath: /
paths:
  '/path-01':
    get:
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Message'
          examples:
            application/json:
              message: 'Hello from get /path-01!'
  '/path-02':
    get:
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Message'
          examples:
            application/json:
              message: 'Hello from get /path-02!'
definitions:
  Message:
    type: object
    properties:
      message:
        type: string