---
# Deploy 'demo-uc-02b' Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: demo-uc-02b
---
# service-a | Deploy 'service-a' Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: demo-uc-02b
---
# service-a | Deploy 'service-a-version-1-0-0-deployment' Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-version-1-0-0-deployment
  namespace: demo-uc-02b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: 1.0.0
      api: acme-api
  template:
    metadata:
      labels:
        app: service-a
        version: 1.0.0
        api: acme-api
    spec:
      serviceAccountName: service-a
      containers:
      - name: service-a
        image: patrice1972/demo-uc-02b-service-a:1.0.0
        ports:
        - name: service-a-port
          protocol: TCP
          containerPort: 3000
---
# service-a | Deploy 'service-a-version-1-0-0' Service
apiVersion: v1
kind: Service
metadata:
  name: service-a-version-1-0-0
  namespace: demo-uc-02b
spec:
  selector:
    app: service-a
    version: 1.0.0
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# service-b | Deploy 'service-b' Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: demo-uc-02b
---
# service-b | Deploy 'service-b-version-1-0-0-deployment' Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-version-1-0-0-deployment
  namespace: demo-uc-02b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: 1.0.0
      api: acme-api
  template:
    metadata:
      labels:
        app: service-b
        version: 1.0.0
        api: acme-api
    spec:
      serviceAccountName: service-b
      containers:
      - name: service-b
        image: patrice1972/demo-uc-02b-service-b:1.0.0
        ports:
        - name: service-a-port
          protocol: TCP
          containerPort: 3000
---
# service-b | Deploy 'service-b-version-1-0-0' Service
apiVersion: v1
kind: Service
metadata:
  name: service-b-version-1-0-0
  namespace: demo-uc-02b
spec:
  selector:
    app: service-b
    version: 1.0.0
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# service-a & service-b | Deploy 'acme-api' Service
apiVersion: v1
kind: Service
metadata:
  name: acme-api
  namespace: demo-uc-02b
spec:
  selector:
    api: acme-api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# client-x | Deploy 'client-x' Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-x
  namespace: demo-uc-02b
---
# client-x | Deploy 'client-x-version-1-0-0-deployment' Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-x-version-1-0-0-deployment
  namespace: demo-uc-02b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-x
      version: 1.0.0
  template:
    metadata:
      labels:
        app: client-x
        version: 1.0.0
    spec:
      serviceAccountName: client-x
      containers:
      - name: client-x
        image: patrice1972/demo-uc-02b-client-x:1.0.0
        env:
        - name: API_HOST
          value: "acme-api.demo-uc-02b"
---
# Deploy 'client-x-version-1-0-0' (dummy) Service [Required by OSM]
apiVersion: v1
kind: Service
metadata:
  name: client-x-version-1-0-0
  namespace: demo-uc-02b
spec:
  selector:
    app: client-x
    version: 1.0.0
  ports:
  - protocol: TCP
    port: 9999
    name: dummy-unused-port